---
- name: Install NATS Prometheus exporter package from the GitHub.
  ansible.builtin.apt:
    state: present
    deb: "https://github.com/nats-io/prometheus-nats-exporter/releases/download/\
      v{{ nats_prometheus_exporter_version }}/\
      prometheus-nats-exporter-\
      v{{ nats_prometheus_exporter_version }}-linux-{{ ansible_architecture }}.deb"

- name: Create the "nats" user & group
  ansible.builtin.import_tasks:
    file: user-group-nats.yaml

- name: Ensure NATS exporter service file is available.
  ansible.builtin.template:
    src: nats-exporter.service.j2
    dest: /etc/systemd/system/nats-exporter.service
    mode: "0644"
    backup: true
  notify:
    - Reload daemon nats-exporter

- name: Ensure NATS exporter service is started and enabled on boot.
  ansible.builtin.service:
    name: nats-exporter
    state: started
    enabled: true
